### ISSUE TITLE
Multichannel ISI returns error

### ISSUE THREAD

**Issue by ImmanuelSamuel** [mariomulansky/PySpike#11]
Running the following:
avrg_spike_profile = spk.spike_profile_multi(spike_trains)

Gives error

**Comment by ImmanuelSamuel** [comment]
Figured out the problem. Dividing the indices leads to floats which is cannot be used to slice the matrix. So I changed the type. Will send a PR soon.

**Comment by mariomulansky** [comment]
I suppose you import division from __future__ ? I think the best fix would be to use // for unambiguous integer division there.

**Comment by ImmanuelSamuel** [comment]
Ah yes. Changed it to //. Thanks. Works great! 
Any plans to implement directionality and other measures from SPIKY?

**Comment by mariomulansky** [comment]
We are working on a multivariate directionality measure right now. We still have to sort out some of the math, but I'm confident we will be able to provide some implementation soon.

If you are interested in other measures to become part of PySpike, please feel invited to open an issue and I will try to expand PySpike's functionality!

**Comment by mariomulansky** [comment]
Just to confirm: If I use
```from __future__ import division```
it does not affect later imports of PySpike and I'm not getting the error. However, if I run the script with ```python -Qnew``` it does affect the integer division in PySpike and the error appears. Is this what you are doing also?

**Comment by mariomulansky** [comment]
Proposed solution merged into develop. This will become part of the next release.
Thanks again for your contribution!

**Comment by ImmanuelSamuel** [comment]
I didn't use ```from _future_ import division``` before importing PySpike. I didn't see that in the docs so I just imported pyspike.

**Comment by mariomulansky** [comment]
Ok I see. Somehow you must be enforcing the new division operator. Are you running your python scripts via ```python -Qnew```, or do you have some global configuration that sets this flag?
Well anyways, the fix should work so it doesn't really matter.

**Comment by ImmanuelSamuel** [comment]
No I am not. I am not aware of a global setting nor have I checked. Nevertheless as you said this would try to overcome differences in Python distributions - winpython, anaconda etc
