### ISSUE TITLE
Multichannel Directionality Measures!

### ISSUE THREAD

**Issue by ImmanuelSamuel** [mariomulansky/PySpike#13]
I would like to have the multichannel directionality measures implemented. Please let me know if you need any help in implementing this. Thanks. This is turning out to be a nice spike analysis tool.

**Comment by mariomulansky** [comment]
Just to make sure: you mean the new method that Thomas presented in a poster at the CNS meeting in Prague? If so, I am about to start implementing that the next days. You can check the coming updates in the develop branch, but I suggest to wait until everything is finalized and I've added some docs. This will then be part of a new version of PySpike.

**Comment by ImmanuelSamuel** [comment]
I was talking about the directionality measures in Spiky. Yes I will keep a tab on the develop branch.

**Comment by mariomulansky** [comment]
There currently is no directionality measure in SPIKY?

**Comment by ImmanuelSamuel** [comment]
Ha ha I was saying that I would like to have the directionality measures in SPIKY on PySpike.

**Comment by mariomulansky** [comment]
But there is no directionality measures in SPIKY, so I still not 100% sure what you are talking about. Can you give a reference, link, formula?

**Comment by ImmanuelSamuel** [comment]
Yes I just saw that. It was there on the side of the page so I assumed it was part of SPIKY. Sorry about that.

**Comment by ImmanuelSamuel** [comment]
http://wwwold.fi.isc.cnr.it/users/thomas.kreuz/Source-Code/Directionality.html

**Comment by mariomulansky** [comment]
Ok I see. This is not part of SPIKY, and we are currently not considering adding this functionality to PySpike either...
However, if there is demand, it could be worth of thinking about that.
We do currently work on another way of analyzing directionality within groups of spike trains, maybe this could be suitable for you?

**Comment by ImmanuelSamuel** [comment]
Good. Yeah I do have groups of spike trains so it would be nice to have that functionality. Do you have the poster that describes what it does?

**Comment by ImmanuelSamuel** [comment]
Hi Mario, is there an update on the directionality feature? I see that there is a branch but somethings are not implemented. Is there any plan to push this feature. It would be nice to have a estimated time for the update so I can plan on which direction to take for my study. Thanks!

**Comment by mariomulansky** [comment]
We have indeed developed a method for measuring directionality: http://iopscience.iop.org/article/10.1088/1367-2630/aa68c3/meta
The python code in this branch implements the functionality in this paper to some extent. A full implementation is provided in Matlab: http://wwwold.fi.isc.cnr.it/users/thomas.kreuz/Source-Code/SPIKY.html
