### ISSUE TITLE
Spike Sync matrix not symmteric

### ISSUE THREAD

**Issue by ImmanuelSamuel** [mariomulansky/PySpike#14]
I see that the Spike Sync matrix is unsymmetric sometimes. What is this supposed to mean?

**Comment by mariomulansky** [comment]
The matrix should always be symmetric, can you provide an example where it isn't?

**Comment by ImmanuelSamuel** [comment]
Ok I figured it out. In one of my conditions since there are no spikes the matrix has 'nan' values.

**Comment by mariomulansky** [comment]
Ah OK, I see.
However, since the latest version, PySpike should also be able to handle empty spike trains without creating NaNs. See e.g.: a35402c208bd0ad31e5e60b6ddc55a3470e7bdde

**Comment by ImmanuelSamuel** [comment]
Hmm interesting. I just downloaded PySpike this week. So there is definitely something going on. Will try to look into this.

**Comment by ImmanuelSamuel** [comment]
Yes I am using 0.3. For now please let me know if I need to set the NaNs to 0 or 1 according to the paper. I will try to get an example later.

**Comment by mariomulansky** [comment]
For two empty spike trains you should get 1.

**Comment by ImmanuelSamuel** [comment]
Is the interpretation valid? Is it right to say that two neurons not firing are synchronized?

**Comment by mariomulansky** [comment]
It is definitely arguable. After some discussion we arrived at this interpretation, with the main argument being that also the absence of spikes contains information. However, if this interferes with your analysis we can try to make another interpretation available.

**Comment by mariomulansky** [comment]
I might have found the problem. It appears when providing some interval to the ```spike_sync_matrix``` function. I've committed a fix to develop 0d7255c

**Comment by ImmanuelSamuel** [comment]
That is great! Also I just want to confirm that the max_tau is in seconds correct? So a max_tau of 5 ms should be written as max_tau=0.005

**Comment by mariomulansky** [comment]
PySpike doesnt use dimensions. So max_tau should be given in the same dimension as the times in your spike trains.

To confirm: Did you try if the fix works for you? Then I would close this issue.

**Comment by ImmanuelSamuel** [comment]
I haven't I installed using pip install and so cant do a git pull and try it out at the moment. I have a deadline to meet soon. Will update once it is done.

**Comment by ImmanuelSamuel** [comment]
Yup that fixed it. Sorry for the late update

**Comment by mariomulansky** [comment]
Hrm ok, are you using the latest version from Github? Can you provide an example so I can check into this?

**Comment by thomaskreuz** [comment]
We checked this with the latest version of PySpike and this issue has been resolved. This includes the case of empty spikes or spike trains with just one spike (see also the closed issue #29). We also double-checked that it works when providing some interval to the spike_sync_matrix function.
