### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by ImmanuelSamuel** [mariomulansky/PySpike#16]
Got through this in the previous install but forgot what I did.

```
/home/immanuel/programs/python-packages/PySpike/pyspike/__init__.py in <module>()
      9            "DiscreteFunc"]
     10 
---> 11 from PieceWiseConstFunc import PieceWiseConstFunc
     12 from PieceWiseLinFunc import PieceWiseLinFunc
     13 from DiscreteFunc import DiscreteFunc

ImportError: No module named 'PieceWiseConstFunc'
```

**Comment by mariomulansky** [comment]
There seems to be something wrong with the installation. Either it is incomplete or you have two PySpike installations that somehow interfere with each other.

**Comment by ImmanuelSamuel** [comment]
I did pip install pyspike and pip freeze shows only one pyspike version

**Comment by mariomulansky** [comment]
Did you try to uninstall and install PySpike again?

What does ```ls /home/immanuel/programs/python-packages/PySpike/pyspike``` give?

**Comment by ImmanuelSamuel** [comment]
After uninstall and reinstalling and importing
```
/home/immanuel/programs/anaconda3/lib/python3.4/site-packages/pyspike/__init__.py in <module>()
      9            "DiscreteFunc"]
     10 
---> 11 from PieceWiseConstFunc import PieceWiseConstFunc
     12 from PieceWiseLinFunc import PieceWiseLinFunc
     13 from DiscreteFunc import DiscreteFunc

ImportError: No module named 'PieceWiseConstFunc'
```
Then ... 
![image](https://cloud.githubusercontent.com/assets/7865018/9919825/48c32c50-5c9d-11e5-8153-ac6dc7b16eba.png)

**Comment by ImmanuelSamuel** [comment]
Arrghh I didn't source activate python2 ... Sorry for the blunder. Also any plans on porting this to python3?

**Comment by mariomulansky** [comment]
Ah OK I see.

Python3 support should not be a big problem, but currently I don't have time to look into this. But I will open another issue for that to work on it later.
