### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by ghost** [mariomulansky/PySpike#22]
When trying to install pyspike via the command "pip install pyspike" in the windows command prompt, I get the following errors:

![screenshot 2016-05-15 18 56 38](https://cloud.githubusercontent.com/assets/19375396/15275545/10577772-1acf-11e6-81b6-e0e0fdbe1f87.png)

Using python 2.7, I have every dependency up to date, by previously updating them via the same command in the windows command prompt. I didn't found similar issues regarding your package on the other issues tickets.

**Comment by mariomulansky** [comment]
From your error message it seems you are using MSVC version 9.0 to compile the C++ code generated by Python. This is a very old version and apparently doesn't implement the ```fmin``` and ```fmax``` functions necessary for PySpike. After a short check I found that those functions have been added to MSVC in version 12: https://msdn.microsoft.com/en-us/library/hh308439(v=vs.110).aspx - so updating your C++ compiler to a newer version should fix this issue.

**Comment by all0ne** [comment]
Thank you for your answer.

I installed the latest version of Visual Studio, which come with the latest version of MSVC++ compiler (2014), but it seems that it is not supported by python 2.7, and while trying to install pypspike with the new command prompt, pip is still trying to use msvc9 for python 2.7, which as you said doesn't implement fmin and fmax functions. 

I am fairly new to programming and I'm using your package for a University project regarding a Python course, so I don't really know how to set which compiler to use while installing your package.

**Comment by mariomulansky** [comment]
I don't use Windows so I don't really know how to configure python to use a different compiler version. However, the C++ codes in PySpike are not requried, PySpike also offers plain Python implementations of all functions. I'm not sure if the installation still finished despite this compile error, but if so you should be able to use it already.

**Comment by all0ne** [comment]
The installation fails because of the compile error, but forcing pyspike not to use cython by setting all cython related variable to False in the setup.py does permit the installation.

Thank you for your answers.

**Comment by thomaskreuz** [comment]
This compiler compatibility issue has been resolved (by not using cython).
