### ISSUE TITLE
Is there a function for calculating delay between spike trains?

### ISSUE THREAD

**Issue by vr2262** [mariomulansky/PySpike#23]
It looks like the `spike_sync` function (https://mariomulansky.github.io/PySpike/#id8) is a measure of synchronization, but is there a function for getting the delay between spike trains?

**Comment by mariomulansky** [comment]
There is currently no such functionality in PySpike. However, synchronization quantifiers can be used to extract delays between spike trains. The basic idea would be to introduce a delay tau for one spike train find a the value tau such that the synchronization between the spike trains is maximal.

**Comment by vr2262** [comment]
Thanks for confirming.
