### ISSUE TITLE
Tutorial example fails with TypeError: data type not understood

### ISSUE THREAD

**Issue by lesshaste** [mariomulansky/PySpike#35]
I tried to follow the simple example from the tutorial http://mariomulansky.github.io/PySpike/#tutorial .  That is:

```
import numpy as np
from pyspike import SpikeTrain

spike_train = SpikeTrain(np.array([0.1, 0.3, 0.45, 0.6, 0.9], [0.0, 1.0]))
```

But this gives:

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-1-25624f7d70f6> in <module>()
>       2 from pyspike import SpikeTrain
>       3 
> ----> 4 spike_train = SpikeTrain(np.array([0.1, 0.3, 0.45, 0.6, 0.9], [0.0, 1.0]))
> 
> TypeError: data type not understood

**Comment by mariomulansky** [comment]
Yes, this is a typo in the tutorial. I believe it should be:
`spike_train = SpikeTrain(np.array([0.1, 0.3, 0.45, 0.6, 0.9]), [0.0, 1.0])`
I'll update the docs.
