### ISSUE TITLE
Adaptive generalizations?

### ISSUE THREAD

**Issue by subhacom** [mariomulansky/PySpike#40]
I was wondering if the adaptive versions of these measures (Satuvuori, et al., 2017, J. Neurosci. Meth.) have been incorporated in this package. I found an AdaptiveISIdistance function example in cSPIKE page, but found no mention of something similar in PySpike. 
If the existing functions can be used for adaptive measures, an example will be very useful.

**Comment by thomaskreuz** [comment]
Dear subhacom,

sorry, it took us some time but the adaptive versions are now included in PySpike. See the documentation for more information.

https://mariomulansky.github.io/PySpike/
