### ISSUE TITLE
Tests should not test for exact equality (tests fail on certain architectures)

### ISSUE THREAD

**Issue by gspr** [mariomulansky/PySpike#44]
My Debian package of PySpike has just been included into the distribution [1]. The build process revealed that some of the included tests fail on certain architectures. I believe you should not be using `assert_equal` in these tests, but rather [`assert_allclose`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.testing.assert_allclose.html#numpy.testing.assert_allclose) and friends to account for slightly different floating point behavior on different architectures.

[1] https://tracker.debian.org/pkg/python-pyspike

**Comment by mariomulansky** [comment]
Firstly, thanks for pushing PySpike into a Debian package!

I only have CI testing on Linux for PySpike so other platforms might have issues indeed. Do you have a build log of the failures somewhere? I followed you link but I couldn't find any. I'd be happy to fix the errors, but it would be very helpful if I had a way to reproduce the failure.

Thanks

**Comment by gspr** [comment]
[Here's](https://buildd.debian.org/status/fetch.php?pkg=python-pyspike&arch=arm64&ver=0.6.0-1&stamp=1583601581&raw=0) a log example. Just search for `FAIL` to find the relevant portion.

I am about to test a fix, and will report back.

**Comment by gspr** [comment]
[This patch](https://nonempty.org/~gspr/tmp/0001-Use-assert_allclose-instead-of-assert_equal-in-tests.patch) seems sufficient. Let me know if you prefer a pull request.

**Comment by mariomulansky** [comment]
Thanks! If it's not too much hassle I would appreciate a PR - please open it against the develop branch. I'll make sure to push a new release from that. I appreciate your efforts here!

PS: PySpike running on ARM64 - that's pretty awesome :)

**Comment by gspr** [comment]
Mario Mulansky <notifications@github.com> writes:

> Thanks! If it's not too much hassle I would appreciate a PR - please
> open it against the develop branch. I'll make sure to push a new
> release from that. I appreciate your efforts here!

I try to avoid using GitHub as much as I can, so here's a non-GitHub
pull request:


The following changes since commit 8ab39a445781175d1c8732d24ff30e90f8d479ab:

  Add missing line in tutorial (2018-09-20 10:58:13 -0700)

are available in the Git repository at:

  https://git.nonempty.org/debian-python-pyspike/ gspr/issue-44

for you to fetch changes up to 9649685210a8b5252b28d8289d2c8258c28ed24b:

  Use assert_allclose instead of assert_equal in tests to allow for different floating point behavior on different architectures or optimization levels. (2020-03-08 11:29:48 +0100)

----------------------------------------------------------------
Gard Spreemann (1):
      Use assert_allclose instead of assert_equal in tests to allow for different floating point behavior on different architectures or optimization levels.

 test/test_distance.py                      | 70 +++++++++++++++---------------
 test/test_empty.py                         | 36 +++++++--------
 test/test_function.py                      | 52 +++++++++++-----------
 test/test_generic_interfaces.py            | 18 ++++----
 test/test_regression/test_regression_15.py | 20 ++++-----
 test/test_spikes.py                        | 10 ++---
 test/test_sync_filter.py                   | 32 +++++++-------
 7 files changed, 119 insertions(+), 119 deletions(-)


> PS: PySpike running on ARM64 - that's pretty awesome :)

Hehe, and a bunch of other architectures too:

 https://buildd.debian.org/status/package.php?p=python-pyspike

How many users there are on those architectures I don't know.

Migration of the package into Ubuntu and other Debian-derived
distributions should happen within a few days too.

**Comment by gspr** [comment]
A gentle ping on this issue, if you don't mind :-)

**Comment by gspr** [comment]
I've also pushed the PR within GitHub's system, if that eases merging.
