### ISSUE TITLE
SPIKE distance value higher than 1

### ISSUE THREAD

**Issue by irenemalvestio** [mariomulansky/PySpike#45]
Hi, in my analysis I found some examples in which the spike distance profile gives values higher than 1 (even around 30) towards the end of the interval. Do you know what can be the reason?

**Comment by xhulianoThe1** [comment]
Can you provide an example?

**Comment by thomaskreuz** [comment]
[ The problem was that there were some spikes that appeared more than once. The new PySpike checks the spike trains first and eliminates any double occurrences. It also sorts the spikes within all spike trains. ]
