### ISSUE TITLE
RFE: Move away from using deprecated nose for testing

### ISSUE THREAD

**Issue by sanjayankur31** [mariomulansky/PySpike#48]
# Feature
nose is deprecated, so it'll be good to move to another testing tool, perhaps py.test.

# Motivation
nose is deprecated upstream (the last commit was in 2016.) and is also being deprecated in Fedora.

https://github.com/nose-devs/nose/commits/master

It is still in use here, though

https://github.com/mariomulansky/PySpike/blob/master/test/test_function.py

The nose website says:

https://nose.readthedocs.io/en/latest/

"Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using Nose2, py.test, or just plain unittest/unittest2."

Deprecation of nose in Fedora: https://fedoraproject.org/wiki/Changes/DeprecateNose

Alternatives
py.test or nose2 (but nose2 doesn't seem to be at par with nose or py.test)

# Additional context

This came up while working on including PySpike in Fedora as part of the [NeuroFedora](neuro.fedoraproject.org) initiative.

**Comment by gspr** [comment]
To add: If PySpike does not migrate away from nose by the end of this year, roughly, I will be forced to drop its Debian package before the next Debian release (Debian 12 "Bookworm"). More information can be found [starting here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1018568).
