### ISSUE TITLE
pip version does not have spike_sync

### ISSUE THREAD

**Issue by orena1** [mariomulansky/PySpike#5]
Hi,
The verison that I got from doing pip install pyspike does not have the spike_sync function.

Also when I do pyspike.\_\_version\_\_ I get
```python
In [92]: pyspike.__version__
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-92-6c310a588f59> in <module>()
----> 1 pyspike.__version__

AttributeError: 'module' object has no attribute '__version__'

```

Thank you for a great package.

**Comment by mariomulansky** [comment]
Hi, thanks for your interest in PySpike.

I have released the new version of pyspike on pypi just a few hours ago. So I think you still have the old version without the spike_sync. If you install now via pip you should get the current version including spike_sync and several other significant changes.

As for the __version__ attribute: indeed I forgot to add this property. I have just commited a change that adds this attribute, so this will become part of pyspike with the next release.

**Comment by orena1** [comment]
Hi,
I installed the new version but now I can not send the functions arrays of spikes..

For example:
```python
train1 = [0,1,5,6,12,14]
train2 = [0,2,4,13,14]
spk.spike_sync(train1,train2)
```

In the old versions it accepted this code..
Thanks

**Comment by mariomulansky** [comment]
Yes, this is a breaking change introduced with the latest version (0.2). Now spike trains are represented by SpikeTrain objects, as described in the docs: http://mariomulansky.github.io/PySpike/

in your example you would now write:
```
train1 = spk.SpikeTrain([1,5,6,12], [0, 14])
```
assuming the the spikes at 0 and 14 where the auxiliary spikes before that defined the beginning and end of the spike train.

**Comment by orena1** [comment]
Ok thanks, I will add a fix to my code?
I do have three offtopic questions that relates to performance.
1. Is is possible that the new version is slower then the old one?
2. Have you checked the speed difference between the matlab version and the python one? do you know which is faster?
3. Have you considered using more then one thread ? http://docs.cython.org/src/userguide/parallelism.html
https://github.com/cython/cython/wiki/enhancements-parallel
specifically in the multi variant form of the functions   ( pike_distance_multi , pike_distance_multi etc.. ) 


Thank You very much,
Oren.

**Comment by mariomulansky** [comment]
1. I have done some brief performance checks and did not experience performance changes with the new version. However, if you seem to observe a performance drop I would be happy to investigate. Good performance is a crucial point in PySpike.
2. I have not done explicit comparison with matlab, but I have gotten some feedback from users that used both and said PySpike seemed faster.
3. I have had a parallel version of the multi-variate distance functions based on pythons threading module that did not give any performance improvements. However, I could try to put the parallelism into the cython code directly, thanks for the links.

What kind of spike trains are you working with that performance becomes crucial?

**Comment by orena1** [comment]
Hi Thank you for the response.

I am using spike trains that I got from simulations..
there are 121 Neurons running 30 seconds at many different simulation settings. Each test is not very slow, but when I test the synchrony of all the settings it get slow.


.3. Are you sure you did not get any better performance , as the multi variant is just many couple analysis.. so I assumed you can just send them to different threads ( for example I have 8 threads , and expect to get 8 time better performance )...  ( you can use htop to see for sure that you use all the cores in the cpu)


Another last point about speed:
I assumed that if I choose a smaller interval for the spike_distance function it will be faster, or am I wrong?
Because it seems that now it takes the same time with long interval or very short one:
```python
In [22]: cProfile.run('spk.spike_distance_multi(STlist,interval=[8500,8700])')
         58119 function calls in 2.008 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    2.008    2.008 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 PieceWiseLinFunc.py:120(avrg)
     7259    0.036    0.000    1.773    0.000 PieceWiseLinFunc.py:155(add)
     7260    0.006    0.000    0.027    0.000 PieceWiseLinFunc.py:17(__init__)
        1    0.000    0.000    0.000    0.000 PieceWiseLinFunc.py:185(mul_scalar)
        1    0.000    0.000    0.000    0.000 PieceWiseLinFunc.py:74(integral)
        2    0.000    0.000    0.000    0.000 PieceWiseLinFunc.py:84(intermediate_value)
        1    0.000    0.000    0.000    0.000 _methods.py:31(_sum)
        2    0.000    0.000    0.000    0.000 _methods.py:40(_all)
        3    0.000    0.000    0.000    0.000 _weakrefset.py:70(__contains__)
        2    0.000    0.000    0.000    0.000 abc.py:128(__instancecheck__)
        1    0.000    0.000    0.000    0.000 fromnumeric.py:1631(sum)
        2    0.000    0.000    0.000    0.000 fromnumeric.py:963(searchsorted)
        1    0.024    0.024    2.007    2.007 generic.py:17(_generic_profile_multi)
        1    0.000    0.000    2.008    2.008 spike_distance.py:101(spike_distance_multi)
     7260    0.027    0.000    0.210    0.000 spike_distance.py:12(spike_profile)
        1    0.000    0.000    2.008    2.008 spike_distance.py:76(spike_profile_multi)
        2    0.000    0.000    0.000    0.000 {getattr}
        3    0.000    0.000    0.000    0.000 {isinstance}
        5    0.000    0.000    0.000    0.000 {len}
        2    0.000    0.000    0.000    0.000 {method 'all' of 'numpy.ndarray' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        3    0.000    0.000    0.000    0.000 {method 'reduce' of 'numpy.ufunc' objects}
        2    0.000    0.000    0.000    0.000 {method 'searchsorted' of 'numpy.ndarray' objects}
        1    0.000    0.000    0.000    0.000 {numpy.core.multiarray.arange}
    21781    0.022    0.000    0.022    0.000 {numpy.core.multiarray.array}
     7259    1.737    0.000    1.737    0.000 {pyspike.cython.cython_add.add_piece_wise_lin_cython}
     7260    0.156    0.000    0.156    0.000 {pyspike.cython.cython_distance.spike_distance_cython}
        1    0.000    0.000    0.000    0.000 {range}



In [23]: cProfile.run('spk.spike_distance_multi(STlist,interval=[1000,31000])')
         58119 function calls in 2.014 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    2.014    2.014 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 PieceWiseLinFunc.py:120(avrg)
     7259    0.037    0.000    1.778    0.000 PieceWiseLinFunc.py:155(add)
     7260    0.006    0.000    0.027    0.000 PieceWiseLinFunc.py:17(__init__)
        1    0.000    0.000    0.000    0.000 PieceWiseLinFunc.py:185(mul_scalar)
        1    0.000    0.000    0.000    0.000 PieceWiseLinFunc.py:74(integral)
        2    0.000    0.000    0.000    0.000 PieceWiseLinFunc.py:84(intermediate_value)
        1    0.000    0.000    0.000    0.000 _methods.py:31(_sum)
        2    0.000    0.000    0.000    0.000 _methods.py:40(_all)
        3    0.000    0.000    0.000    0.000 _weakrefset.py:70(__contains__)
        2    0.000    0.000    0.000    0.000 abc.py:128(__instancecheck__)
        1    0.000    0.000    0.000    0.000 fromnumeric.py:1631(sum)
        2    0.000    0.000    0.000    0.000 fromnumeric.py:963(searchsorted)
        1    0.025    0.025    2.013    2.013 generic.py:17(_generic_profile_multi)
        1    0.000    0.000    2.014    2.014 spike_distance.py:101(spike_distance_multi)
     7260    0.027    0.000    0.211    0.000 spike_distance.py:12(spike_profile)
        1    0.000    0.000    2.013    2.013 spike_distance.py:76(spike_profile_multi)
        2    0.000    0.000    0.000    0.000 {getattr}
        3    0.000    0.000    0.000    0.000 {isinstance}
        5    0.000    0.000    0.000    0.000 {len}
        2    0.000    0.000    0.000    0.000 {method 'all' of 'numpy.ndarray' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        3    0.000    0.000    0.000    0.000 {method 'reduce' of 'numpy.ufunc' objects}
        2    0.000    0.000    0.000    0.000 {method 'searchsorted' of 'numpy.ndarray' objects}
        1    0.000    0.000    0.000    0.000 {numpy.core.multiarray.arange}
    21781    0.022    0.000    0.022    0.000 {numpy.core.multiarray.array}
     7259    1.741    0.000    1.741    0.000 {pyspike.cython.cython_add.add_piece_wise_lin_cython}
     7260    0.156    0.000    0.156    0.000 {pyspike.cython.cython_distance.spike_distance_cython}
        1    0.000    0.000    0.000    0.000 {range}
```

**Comment by mariomulansky** [comment]
How many spikes do you typically have in your spike trains?

The problem with my first approach using python's threading package might be the overhead due to the starting of new threads for each distance. Using OMP based parallelization within cython should improve things and give reasonable scaling with the number of cores used.

To your last point: No, you dont get better performance by using smaller intervals, because it  computes the full profile first and then only uses the limits for the averaging of the profile. However, if you cut your spike trains before to the shorter interval the computation will be faster.

**Comment by mariomulansky** [comment]
Hi Oren,

I have had another look at the performance of the multivariate implementations and through some tricks I was able to introduce significant performance gains. Check a0262fc if you are interested in the changes.

If you want to test these faster implementation you can check out the develop branch from github. Otherwise you will have to wait for a new release of PySpike on pypi, which I'm planning for next week.

**Comment by orena1** [comment]
Thanks.
I think it is faster.

**Comment by mariomulansky** [comment]
I have just release PySpike 0.3. You can install it from pypi and it includes all the performance improvements mentioned above.
With this, I'm closing this issue, if you have any more problems, please open a new one here.
Thanks a lot for your input!
