### ISSUE TITLE
The link to the SPIKY framework is invalid

### ISSUE THREAD

**Issue by shixiaopei** [mariomulansky/PySpike#50]
Hi,
I am a graduate student and want to learn the relevant knowledge of analyzing spike train from the papers and codes you published.
I am more familiar with the MATLAB language, but the link to the SPIKY framework is no longer valid. If it is convenient for you to give me a new link to the SPIKY framework, that would be great.

Can you help me solve this problem？ Thanks

**Comment by xhulianoThe1** [comment]
^ Created a pull request to update the links. 

For your purposes this is the new updated link: 
https://thomas-kreuz.complexworld.net/source-codes/spiky

**Comment by mariomulansky** [comment]
Thanks for the PR #54 @xhulianoThe1 - I've merged it and made it part of a the new release 0.7.0.
