### ISSUE TITLE
PySpike incompatible with Python 3.10

### ISSUE THREAD

**Issue by gspr** [mariomulansky/PySpike#52]
Python 3.7 started issuing a warning that importing abstract base classes like `Sequence` from `collections` instead of `collections.abc` is deprecated. With Python 3.10, doing so is an error. That means that PySpike does not work with Python 3.10 or later. That should be fixed, and doing so should be easy.

More info e.g. [here](https://stackoverflow.com/a/69598162).

**Comment by gspr** [comment]
[PR 53](https://github.com/mariomulansky/PySpike/pull/53) fixes the issue, but may result in incompatibilities with some very old Python versions. If you wanna retain compatibility with those, the PR can be adapted to try both the old and the new import.

**Comment by gspr** [comment]
The merging of PR 53 fixes this.

**Comment by mariomulansky** [comment]
Thanks for the PR @gspr - I decided to drop Python2 support and anything older than Python 3.7.
