### ISSUE TITLE
PySpike incompatible with NumPy ≥1.24.0

### ISSUE THREAD

**Issue by gspr** [mariomulansky/PySpike#63]
NumPy 1.24.0 finally [deprecated some type aliases](https://numpy.org/devdocs/release/1.24.0-notes.html#expired-deprecations). These include `np.float`, which is used in a few places in PySpike. It should be pretty straightforward to get rid of these (in favour of a plain Python `float`). This is necessary in order to be able to use PySpike with NumPy 1.24.0 and later.

**Comment by EdmundButler** [comment]
No occurrences of np.float are left and PySpike works with numpy 1.24

**Comment by gspr** [comment]
Ah, sorry, I didn't notice the large amount of recent changes.

Would it be possible to make a tagged, versioned release sometime soon?

**Comment by thomaskreuz** [comment]
We will first try to address and close all open issues. As soon as this is done we will release a new version.
