### ISSUE TITLE
0.8.0 release on Pypi but not tagged on GitHub

### ISSUE THREAD

**Issue by sanjayankur31** [mariomulansky/PySpike#71]
Hi there,

I see a 0.8.0 release on PyPi here: https://pypi.org/project/pyspike/#history

but I do not see this tagged on GitHub. Could it please be tagged here? It just makes it easier for us downstream Linux distributions to package it.

Thanks very much.

**Comment by sanjayankur31** [comment]
Hello,

Could someone please take a look at this when possible?

Cheers,

**Comment by mariomulansky** [comment]
Thanks for raising this, I did indeed forget to tag the new release, I have now added a tag for 0.8.0 - I hope this helps and makes your live easier!
Cheers!
