### ISSUE TITLE
Generated file `pyspike/cython/cython_simulated_annealing.c` erroneously tracked by git

### ISSUE THREAD

**Issue by gspr** [mariomulansky/PySpike#72]
Version 0.8.0 ships with the generated file `pyspike/cython/cython_simulated_annealing.c`  erroneously tracked by git. Please consider dropping it from the git repository, and creating a new release (this is significant for the PySpike package that I maintain in Debian). Thanks!

**Comment by kay-horst** [comment]
There was a misunderstanding – #78 did not fix this issue, but rather was a precondition for the current one, as it added `.gitignore`.

I did not want to do both in one step to make the change for the current issue more transparent.

**Comment by thomaskreuz** [comment]
Resolved. Thanks!
